#!/bin/bash

ACC="\033[36m"
ERR="\033[31m"
NC="\033[0m"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "${DIR}/.."

if [ ! -f ./build/release/neuralnet ] || [[ $1 =~ ^"-{1,2}[Yy]"$ ]]; then
    echo -e "${ACC}Release build not found in build directory."
    read -p "Would you like to build now? (y/N) " -n 1 -r
    echo -e -n "${NC}\n"
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
        DID_BUILD=1
        ./script/build release || exit 1
    else
        echo -e "\n${ACC}Build cancelled.${NC}\n" 
        exit 0
    fi
fi

rm -f -r "./dist"
mkdir -p "./dist"
zip ./dist/exec.zip ./build/release/neuralnet ./docs/*
git archive --output="./dist/project.zip" HEAD

echo -e "\n${ACC}Build output copied to \"./dist\".${NC}\n"

exit 0